security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: name

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: /                # Página de inicio como página de login
                check_path: /login            # Ruta donde Symfony verifica las credenciales
                default_target_path: /user    # Redirigir después de login exitoso
                failure_path: /               # Redirigir al login en caso de fallo
                failure_forward: false        # Redirige de nuevo al login en caso de error
                always_use_default_target_path: true
                enable_csrf: true             # CSRF protection en el formulario de login

            logout:
                path: app_logout
                target: /                    # Redirige a / después del logout

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
